name: "📚 Documentation Improvement"
description: Suggest changes or additions to the documentation.
labels: [documentation]
title: "[Docs] <short description>"
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Improvement
        Please describe the documentation issue or improvement you suggest.
  - type: input
    id: location
    attributes:
      label: Location
      description: Where in the documentation does this need improvement?
      placeholder: "e.g. docs/guide/integration/getting-started.md"
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: What would you like to change or add?
      placeholder: "Describe your suggestion."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references.
      placeholder: "Add context here."
    validations:
      required: false

